const { AMENDMENT_STATUS } = require('./amendmentStatus');

const AMENDMENT_ACTION = Object.freeze({
  PUT_FOLLOW_UP: 'put_follow_up',
  MARK_PENDING: 'mark_pending',
  MARK_LOSS: 'mark_loss',
  MARK_WON: 'mark_won',
});

const AMENDMENT_ACTION_VALUES = Object.values(AMENDMENT_ACTION);

const ACTION_TO_STATUS = Object.freeze({
  [AMENDMENT_ACTION.PUT_FOLLOW_UP]: AMENDMENT_STATUS.FOLLOWUP,
  [AMENDMENT_ACTION.MARK_PENDING]: AMENDMENT_STATUS.PENDING,
  [AMENDMENT_ACTION.MARK_LOSS]: AMENDMENT_STATUS.LOSS,
  [AMENDMENT_ACTION.MARK_WON]: AMENDMENT_STATUS.COMPLETED,
});

module.exports = {
  AMENDMENT_ACTION,
  AMENDMENT_ACTION_VALUES,
  ACTION_TO_STATUS,
};
